package reports

import (
	"context"
	"log/slog"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// TaxHijack is income tax hijacked into another country, with the amount.
type TaxHijack struct {
	CountryID bson.ObjectID `bson:"countryId"`
	Amount    float64       `bson:"amount"`
}

// ForeignTaxRecipient is income tax redirected to a citizen's home country.
type ForeignTaxRecipient struct {
	CountryID bson.ObjectID `bson:"countryId"`
	Amount    float64       `bson:"amount"`
}

// TaxSource is the tax contribution generated by users of a given home country.
type TaxSource struct {
	CountryID            bson.ObjectID `bson:"countryId"`
	Total                float64       `bson:"total"`
	Hijacked             float64       `bson:"hijacked"`
	CorePct              float64       `bson:"corePct"`
	ForeignTaxRedirected float64       `bson:"foreignTaxRedirected,omitempty"`
}

// CountryTaxFlow is the hourly income-tax flow report for one country.
type CountryTaxFlow struct {
	ID                   string                `bson:"_id"`
	CountryID            bson.ObjectID         `bson:"countryId"`
	HourStart            time.Time             `bson:"hourStart"`
	TotalTax             float64               `bson:"totalTax"`
	HijackedIn           float64               `bson:"hijackedIn"`
	CoreEarned           float64               `bson:"coreEarned"`
	NonCoreEarned        float64               `bson:"nonCoreEarned"`
	HijackedOut          float64               `bson:"hijackedOut"`
	Hijackers            []TaxHijack           `bson:"hijackers"`
	ForeignTaxIn         float64               `bson:"foreignTaxIn,omitempty"`
	ForeignTaxOut        float64               `bson:"foreignTaxOut,omitempty"`
	ForeignTaxRecipients []ForeignTaxRecipient `bson:"foreignTaxRecipients,omitempty"`
	Sources              []TaxSource           `bson:"sources"`
}

// CountryTaxFlowID is the deterministic per-country-per-hour key.
func CountryTaxFlowID(countryID bson.ObjectID, hourStart time.Time) string {
	return countryID.Hex() + "@" + hourStart.UTC().Format(time.RFC3339)
}

type CountryTaxFlowStore struct {
	coll *mongo.Collection
}

func NewCountryTaxFlowStore(ctx context.Context, db *mongo.Database) *CountryTaxFlowStore {
	store := &CountryTaxFlowStore{coll: db.Collection("country_tax_flows")}
	store.ensureIndex(ctx)
	return store
}

func (s *CountryTaxFlowStore) ensureIndex(ctx context.Context) {
	_, err := s.coll.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "countryId", Value: 1}, {Key: "hourStart", Value: -1}},
	})
	if err != nil {
		slog.Error("Failed creating compound index on country_tax_flows.{countryId,hourStart}", "error", err)
	}
}

// Upsert replaces a batch of hourly tax-flow rows keyed on _id.
func (s *CountryTaxFlowStore) Upsert(ctx context.Context, rows []CountryTaxFlow) error {
	if len(rows) == 0 {
		return nil
	}
	ops := make([]mongo.WriteModel, len(rows))
	for i := range rows {
		ops[i] = mongo.NewReplaceOneModel().
			SetFilter(bson.D{{Key: "_id", Value: rows[i].ID}}).
			SetReplacement(rows[i]).
			SetUpsert(true)
	}
	_, err := s.coll.BulkWrite(ctx, ops, options.BulkWrite().SetOrdered(false))
	return err
}
